name = "sh-lp"
compatibility_date = "2024-08-28"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "KV"
id = "6628af007e344e88b823b469274064c8"

[vars]
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
